### ISSUE TITLE
Building wheel for scipy (setup.py) ... error

### ISSUE THREAD

**Issue by shini-tm** [ideo/LaughDetection#10]
```
Building wheels for collected packages: scipy
  Building wheel for scipy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\shini\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shini\\AppData\\Local\\Temp\\pip-install-wqaljajm\\scipy_9a7c2cb476df44de81c29e37b8c50ffb\\setup.py'"'"'; __file__='"'"'C:\\Users\\shini\\AppData\\Local\\Temp\\pip-install-wqaljajm\\scipy_9a7c2cb476df44de81c29e37b8c50ffb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\shini\AppData\Local\Temp\pip-wheel-75wx115c'
       cwd: C:\Users\shini\AppData\Local\Temp\pip-install-wqaljajm\scipy_9a7c2cb476df44de81c29e37b8c50ffb\
  Complete output (31 lines):
  Traceback (most recent call last):
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
      from . import multiarray
  ImportError: DLL load failed: The specified procedure could not be found.
```
After running `pip install -r requirements.txt` it seems to fail at scipy. Using a conda environment. Windows 10.
When i try `python live_inference.py --save_file='\path\to\output.csv'` I believe the same library is causing the issue. 
```
(laugh) PS C:\Users\shini\Documents\GitHub\LaughDetection> python live_inference.py --save_file='\path\to\output.csv'
Traceback (most recent call last):
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "live_inference.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\shini\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified procedure could not be found.
```
But in the requirements.txt there is no scipy=XX so i'm not sure

**Comment by shini-tm** [comment]
reinstalling numpy seems to fix it: `pip install --upgrade --force-reinstall numpy`

**Comment by shini-tm** [comment]
i just realised it still doesn't resolve the wheel for scipy issue. Tried to run `pip install -r requirements.txt --no-cache-dir ` but everything other than wheel scipy seems to work giving rise to lots of NOT AVAILABLE errors: 
```
  Building wheel for scipy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\shini\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shini\\AppData\\Local\\Temp\\pip-install-e_5q2ij2\\scipy_d25c7706f1ae465b91befd974c231d8c\\setup.py'"'"'; __file__='"'"'C:\\Users\\shini\\AppData\\Local\\Temp\\pip-install-e_5q2ij2\\scipy_d25c7706f1ae465b91befd974c231d8c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\shini\AppData\Local\Temp\pip-wheel-hu9djih4'
       cwd: C:\Users\shini\AppData\Local\Temp\pip-install-e_5q2ij2\scipy_d25c7706f1ae465b91befd974c231d8c\
  Complete output (147 lines):
  lapack_opt_info:
  lapack_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\lib', 'C:\\', 'c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\libs', 'C:\\Users\\shini\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\lib', 'C:\\', 'c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\libs', 'C:\\Users\\shini\\anaconda3\\Library\\lib']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'     
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE

  openblas_clapack_info:
    libraries openblas,lapack not found in ['c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\lib', 'C:\\', 'c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\libs', 'C:\\Users\\shini\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  flame_info:
    libraries flame not found in ['c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\lib', 'C:\\', 'c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\libs', 'C:\\Users\\shini\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries tatlas,tatlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries tatlas,tatlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries lapack_atlas not found in C:\Users\shini\anaconda3\Library\lib
    libraries tatlas,tatlas not found in C:\Users\shini\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries satlas,satlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries satlas,satlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries lapack_atlas not found in C:\Users\shini\anaconda3\Library\lib
    libraries satlas,satlas not found in C:\Users\shini\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries ptf77blas,ptcblas,atlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries ptf77blas,ptcblas,atlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries lapack_atlas not found in C:\Users\shini\anaconda3\Library\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\shini\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries f77blas,cblas,atlas not found in c:\users\shini\appdata\local\programs\python\python36\lib
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries f77blas,cblas,atlas not found in c:\users\shini\appdata\local\programs\python\python36\libs
    libraries lapack_atlas not found in C:\Users\shini\anaconda3\Library\lib
    libraries f77blas,cblas,atlas not found in C:\Users\shini\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\lib', 'C:\\', 'c:\\users\\shini\\appdata\\local\\programs\\python\\python36\\libs', 'C:\\Users\\shini\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  lapack_src_info:
    NOT AVAILABLE

  c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\shini\AppData\Local\Temp\pip-install-e_5q2ij2\scipy_d25c7706f1ae465b91befd974c231d8c\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\shini\AppData\Local\Temp\pip-install-e_5q2ij2\scipy_d25c7706f1ae465b91befd974c231d8c\setup.py", line 412, in setup_package    
      setup(**metadata)
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\shini\AppData\Local\Temp\pip-install-e_5q2ij2\scipy_d25c7706f1ae465b91befd974c231d8c\setup.py", line 336, in configuration    
      config.add_subpackage('scipy')
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1020, in add_subpackage    
      caller_level = 2)
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 989, in get_subpackage     
      caller_level = caller_level + 1)
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1020, in add_subpackage    
      caller_level = 2)
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 989, in get_subpackage     
      caller_level = caller_level + 1)
    File "c:\users\shini\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
  ----------------------------------------
  ERROR: Failed building wheel for scipy
  Running setup.py clean for scipy
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\shini\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shini\\AppData\\Local\\Temp\\pip-install-e_5q2ij2\\scipy_d25c7706f1ae465b91befd974c231d8c\\setup.py'"'"'; __file__='"'"'C:\\Users\\shini\\AppData\\Local\\Temp\\pip-install-e_5q2ij2\\scipy_d25c7706f1ae465b91befd974c231d8c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\shini\AppData\Local\Temp\pip-install-e_5q2ij2\scipy_d25c7706f1ae465b91befd974c231d8c
  Complete output (9 lines):

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for scipy
```

**Comment by shini-tm** [comment]
im thinking it has something to do with the python version. what python version was used for the project?

**Comment by nsteins** [comment]
I think this was probably with 3.6, though I never pinned the python version. (There's a major lesson I've learned in the past 3 years, pip freeze is not a super useful dependency management system)

I never tested this on Windows, and the error messages you are receiving seem to indicate missing C libraries, which suggest there might be an issue with your Anaconda install, or you have PATH issues.

Are you able to install scipy, any version, in a clean environment?

**Comment by shini-tm** [comment]
I would guess its 3.6.4 based on the commit timings. But I think you're right. cant install scipy in a new environment get the same errors.
I dont think its a PATH issue as everything appears setup:
![image](https://user-images.githubusercontent.com/31591116/110401642-d9488380-8071-11eb-918c-89d233206e49.png)

**Comment by shini-tm** [comment]
trying to see if i can find those libraries. thanks for the help !

**Comment by nsteins** [comment]
have you tried `conda install scipy`? 
Conda runs its own repos, which sometimes work for the tricky C-based libraries.

**Comment by shini-tm** [comment]
it does successfully install but i get scipy 1.5.2, let me install the latest libraries and see if it works.

**Comment by shini-tm** [comment]
if i run the conda equivalent `conda install --file requirements.txt` I get:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - dash_core_components==0.22.1
  - dash==0.21.0
  - resampy==0.2.0
  - tensorflow==1.2.1
  - phue==1.0
  - keras==2.0.6
  - dash_html_components==0.10.0
  - dash-renderer==0.12.1
```
but fortunately scipy is 0.19.1 :DD

**Comment by shini-tm** [comment]
couldn't find the appropriate versions of the older dash & dash_html_components. phue seems to only be linux in the conda-forge repo but fortunately i dont need the phue functionality. Everything else seemed to work out.

**Comment by nsteins** [comment]
Glad you got it worked out! For what it's worth, I believe you can use a mixture of conda and pip. Or see if there are older versions on conda-forge.
