### ISSUE TITLE
issue with using model trained following your notebooks steps

### ISSUE THREAD

**Issue by byassin** [ideo/LaughDetection#8]
Hi there,

Thanks for putting this together... when I follow the steps you have outlined in your notebook and try to recreate the same model you use in this example I get the following error when I run the script to give the laughter score:

Traceback (most recent call last):
  File "infer_audio.py", line 54, in <module>
    p = predict_laugh(np.expand_dims(processed_embedding, axis=0))
  File "infer_audio.py", line 36, in predict_laugh
    model = keras.models.load_model(FLAGS.keras_model)
  File "C:\Python36\lib\site-packages\keras\models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Python36\lib\site-packages\keras\models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Python36\lib\site-packages\keras\layers\__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "C:\Python36\lib\site-packages\keras\utils\generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Python36\lib\site-packages\keras\models.py", line 1204, in from_config
    if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
KeyError: 0

Any help would be appreciated. Thanks

**Comment by byassin** [comment]
Thanks @nsteins. As soon as I downgraded Keras on the Jupyter notebook, it worked like a charm.
